---
# hack, Ansible is too fast.
- name: Magic wait to make ipa-client-install work
  tags:
    - ipa-client
    - ipa-install
  command: sleep 10
  args:
    creates: /etc/ipa/default.conf

- name: join FreeIPA
  tags:
    - ipa-client
    - ipa-install
  command: >
    ipa-client-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --principal admin
    --password {{ ipa_admin_password }}
    --request-cert
    --force-join
  args:
    creates: /etc/ipa/default.conf
