---
# required because present of ca.crt and default.conf doesn't mean
# that the client has been fully configured yet.
- name: signal FreeIPA client has been configured
  tags:
    - ipa
    - ipa-install
  copy:
    content="PKI playbook"
    dest=/etc/ipa/CLIENT_INSTALLED
