---
# we modify the file later but need the original DNS forwarder
- name: make a copy of original resolv.conf
  tags:
    - ipa
  command: cp /etc/resolv.conf /etc/resolv.conf.orig
  args:
    creates: /etc/resolv.conf.orig

- name: Get default DNS
  tags:
    - ipa
  resolver: resolvconf=/etc/resolv.conf.orig
  register: dns_forwarder
  changed_when: false

- name: Get reverse zone
  tags:
    - ipa
  reversezone: ipaddress={{ ansible_default_ipv4.address }}
  register: reversezone
  changed_when: false

- name: Remove chrony (FreeIPA uses ntpd)
  tags:
    - ipa
    - package-install
  yum: name=chrony state=absent

- name: install FreeIPA client package (Fedora)
  tags:
    - ipa
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
   - freeipa-client
   - freeipa-admintools
  when: ansible_distribution == "Fedora" and package_install

- name: install FreeIPA client package (RHEL / CentOS)
  tags:
    - ipa
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
   - ipa-client
   - ipa-admintools
  when: "{{ ansible_distribution in ['RedHat', 'CentOS'] and package_install }}"

- name: Check for mod_ssl configuration
  tags:
    - ipa
    - ipa-install
  stat: path=/etc/httpd/conf.d/ssl.conf
  register: ssl_conf

- name: Disable mod_ssl configuration
  tags:
    - ipa
    - ipa-install
  copy:
    src=replaced
    dest={{ item }}
    backup=true
    owner=root
    group=root
    mode=644
  with_items:
    - /etc/httpd/conf.d/ssl.conf
    - /etc/httpd/conf.modules.d/00-ssl.conf
  when: ssl_conf.stat.exists
  notify:
    - stop httpd

- name: get IPA version
  tags:
    - ipa
  command: ipa --version
  register: ipa_version
  changed_when: false

- name: Check for /etc/ipa/ca.crt
  tags:
    - ipa
  stat: path=/etc/ipa/ca.crt
  register: stat_ipa_cacrt
  changed_when: false

- name: Check for /etc/ipa/default.conf
  tags:
    - ipa
  stat: path=/etc/ipa/default.conf
  register: stat_ipa_defaultconf
  changed_when: false

- name: Set ipa_installed fact
  tags:
    - ipa
  set_fact: ipa_installed="{{ stat_ipa_cacrt.stat.exists and stat_ipa_defaultconf.stat.exists }}"
  changed_when: false
