---
- name: install FreeIPA client package
  tags:
    - ipa
    - packages
    - network
  yum: name=freeipa-client state=present
  when: network_access

- name: get IPA version
  tags:
    - ipa
    - packages
    - network
  command: ipa --version
  register: ipaversion
  changed_when: false
