---
# we modify the file later but need the original DNS forwarder
- name: make a copy of original resolv.conf
  tags:
    - ipa
  command: cp /etc/resolv.conf /etc/resolv.conf.orig
  args:
    creates: /etc/resolv.conf.orig

- name: Get default DNS
  tags:
    - ipa
  resolver: resolvconf=/etc/resolv.conf.orig
  register: dns_forwarder
  changed_when: false

- name: Get reverse zone
  tags:
    - ipa
  reversezone: ipaddress={{ ansible_default_ipv4.address }}
  register: reversezone
  changed_when: false

- name: Remove chrony (FreeIPA uses ntpd)
  tags:
    - ipa
    - package-install
  package: name=chrony state=absent

- name: install FreeIPA client package
  tags:
    - ipa
    - package-install
    - network
  package: name={{ item }} state=present
  with_items:
   - ipa-client
   - ipa-admintools
  when: package_install

- name: Check for mod_ssl configuration
  tags:
    - ipa
  stat: path=/etc/httpd/conf.d/ssl.conf
  register: ssl_conf

- name: Disable mod_ssl configuration
  tags:
    - ipa
  copy:
    src=replaced
    dest={{ item }}
    backup=true
    owner=root
    group=root
    mode=0644
  with_items:
    - /etc/httpd/conf.d/ssl.conf
    - /etc/httpd/conf.modules.d/00-ssl.conf
  when: ssl_conf.stat.exists
  notify:
    - stop httpd

- name: Gather IPA facts
  tags:
    - ipa
  ipa_facts: domain={{ ipa_domain }}

