---
- name: install FreeIPA client package (Fedora)
  tags:
    - ipa
    - package-install
    - network
  yum: name=freeipa-client state=present
  when: ansible_distribution == "Fedora"

- name: install FreeIPA client package (RHEL / CentOS)
  tags:
    - ipa
    - package-install
    - network
  yum: name=ipa-client state=present
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: get IPA version
  tags:
    - ipa
  command: ipa --version
  register: ipa_version
  changed_when: false

- name: Check for /etc/ipa/ca.crt
  tags:
    - ipa
  stat: path=/etc/ipa/ca.crt
  register: stat_ipa_cacrt
  changed_when: false

- name: Check for /etc/ipa/default.conf
  tags:
    - ipa
  stat: path=/etc/ipa/ca.crt
  register: stat_ipa_defaultconf
  changed_when: false

- name: Set ipa_installed fact
  tags:
    - ipa
  set_fact: ipa_installed="{{ stat_ipa_cacrt.stat.exists and stat_ipa_defaultconf.stat.exists }}"
  changed_when: false
