---
- name: Install FreeIPA master (5-7 minutes)
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    ipa-server-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --hostname {{ ansible_fqdn }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --ip-address {{ ansible_default_ipv4.address }}
    --setup-dns
    --mkhomedir
    --ssh-trust-dns
    --reverse-zone={{ reversezone.reversezone }}
    {{ '--forwarder=%s' % dns_forwarder['nameservers'][0] if enable_network else '--no-forwarders' }}
  when: not ipa_installed

- name: Install KRA on FreeIPA master (2-3 minutes)
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/pki/pki-tomcat/kra/CS.cfg

# XXX workaround for race condition
# KRA restarts LDAP, which disconnects bind-ldap plugin. The reconnect
# interval is 60 seconds. A restart make sure named is working properly.
- name: Make sure named-pkcs11 DNS is restarted
  tags:
    - ipaserver-master
    - ipa-install
  service: name=named-pkcs11 state=restarted
  changed_when: false

- name: wait for services to come up
  tags:
    - ipaserver-master
    - ipa-install
  wait_for: port={{ item }} delay=0 timeout=30
  with_items:
    - 53
    - 88
    - 464
    - 749
    - 389
    - 636
    - 80
    - 443
    - 8080
    - 8443

- name: Set sensible defaults
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --defaultshell=/bin/bash"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Set home directory to /export/home
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --homedirectory=/export/home"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Set admin's home directory to /export/home/admin
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="user-mod admin --homedir=/export/home/admin"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable password and OTP loging
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --user-auth-type=password --user-auth-type=otp"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable global DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnsconfig-mod --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnszone-mod {{ ansible_domain }}. --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable reverse DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnszone-mod {{ reversezone.reversezone }} --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: change resolv.conf to use FreeIPA DNS on all IPA systems
  tags:
    - ipaserver-master
    - ipa-install
  template: src=etc_resolvconf dest=/etc/resolv.conf
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipaserver_master'] + groups['ipaserver_replica'] + groups['ipa_client'] + groups['ipa_nfsserver'] }}"

- name: signal FreeIPA master has been deployed
  tags:
    - ipaserver-master
    - ipa-install
  copy:
    content="PKI playbook"
    dest=/etc/ipa/MASTER_DEPLOYED

- include: ../../ipa-client/tasks/ipaclientinstalled.yml

- name: Create Firefox prefs
  tags:
    - ipaserver-master
    - ipa-install
  template: src=firefox_prefs dest=/etc/ipa/prefs.js

- name: Fetch Firefox prefs
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/ipa/prefs.js
         dest={{ vagrant_root }}/inventory/prefs.js
         flat=yes

- name: Fetch krb5config
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/krb5.conf
         dest={{ vagrant_root }}/inventory/krb5.conf
         flat=yes

- name: Fetch resolv.conf
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/resolv.conf
         dest={{ vagrant_root }}/inventory/resolv.conf
         flat=yes

- name: Fetch cacert
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/ipa/ca.crt
         dest={{ vagrant_root }}/inventory/ca.crt
         flat=yes

- name: Fetch ipa default.conf
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/ipa/default.conf
         dest={{ vagrant_root }}/inventory/default.conf
         flat=yes

- name: Fetch kra agent pem file
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch: src=/etc/httpd/alias/kra-agent.pem dest={{ vagrant_root }}/inventory/kra-agent.pem flat=yes
