---
- name: install FreeIPA master (5-7 minutes)
  tags:
    - ipaserver-master
    - install
  command: >
    ipa-server-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --hostname {{ ansible_fqdn }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --reverse-zone {{ reversezone.reversezone }}
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ dns_forwarder.nameservers[0] }}
  args:
    creates: /etc/ipa/default.conf

- name: install KRA on FreeIPA master (2-3 minutes)
  tags:
    - ipaserver-master
    - install
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/pki/pki-tomcat/kra/CS.cfg

- name: Make sure named-pkcs11 DNS is running
  tags:
    - ipaserver-master
    - install
  service: name=named-pkcs11 state=started

- name: wait for services to come up
  tags:
    - ipaserver-master
    - install
  wait_for: port={{ item }} delay=0 timeout=30
  with_items:
    - 53
    - 88
    - 389
    - 80
    - 443

- name: Enable DNS sync ptr
  tags:
    - ipaserver-master
    - install
    - dns
  ipa:
    args="dnszone-mod {{ ansible_domain }}. --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
  register: result
  ignore_errors: true
  failed_when: "result.rc != 0 and 'no modifications' not in result.stderr"

- name: Enable reverse DNS sync ptr
  tags:
    - ipaserver-master
    - install
  ipa:
    args="dnszone-mod {{ reversezone.reversezone }} --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
  register: result
  failed_when: "result.rc != 0 and 'no modifications' not in result.stderr"

- name: sync client clocks
  tags:
    - ipaserver-master
    - install
  command: ntpdate {{ ansible_default_ipv4.address }}
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipa_client'] }}"
  register: result
  failed_when: "result.rc !=0 and 'NTP socket is in use' not in result.stderr"
  changed_when: result.rc == 0

- name: change replicas' resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
    - install
  template: src=etc_resolvconf dest=/etc/resolv.conf
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipaserver_replica'] }}"

- name: change clients' resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
    - install
  template: src=etc_resolvconf dest=/etc/resolv.conf
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipa_client'] }}"

- name: change master's resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
    - install
  template: src=etc_resolvconf dest=/etc/resolv.conf

- name: signal FreeIPA master has been deployed
  tags:
    - ipaserver-master
    - install
  file: path=/etc/ipa/MASTER_DEPLOYED state=touch

- name: Create Firefox prefs
  tags:
    - ipaserver-master
    - install
  template: src=firefox_prefs dest=/etc/ipa/prefs.js

- name: Fetch Firefox prefs
  tags:
    - ipaserver-master
    - install
    - fetch
  fetch: src=/etc/ipa/prefs.js
         dest={{ vagrant_root }}/inventory/prefs.js
         flat=yes

- name: Fetch krb5config
  tags:
    - ipaserver-master
    - install
    - fetch
  fetch: src=/etc/krb5.conf
         dest={{ vagrant_root }}/inventory/krb5.conf
         flat=yes

- name: Fetch cacert
  tags:
    - ipaserver-master
    - install
    - fetch
  fetch: src=/etc/ipa/ca.crt
         dest={{ vagrant_root }}/inventory/ca.crt
         flat=yes

- name: Fetch kra agent pem file
  tags:
    - ipaserver-master
    - install
    - fetch
  fetch: src=/etc/httpd/alias/kra-agent.pem dest={{ vagrant_root }}/inventory/kra-agent.pem flat=yes
