---
- name: install FreeIPA master
  tags:
    - ipaserver-master
  command: >
    ipa-server-install -U
    --realm {{ ipa_realm }}
    --domain {{ ipa_realm | lower }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ dns_forwarder.nameservers[0] }}
  args:
    creates: /etc/ipa/ca.crt

- name: install KRA on FreeIPA master
  tags:
    - ipaserver-master
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/httpd/alias/kra-agent.pem

- name: Fetch krb5config
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/krb5.conf
         dest={{ vagrant_root }}/krb5.conf
         flat=yes

- name: Fetch cacert
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/ipa/ca.crt
         dest={{ vagrant_root }}/ca.crt
         flat=yes

- name: Fetch kra agent pem file
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/httpd/alias/kra-agent.pem dest={{ vagrant_root }}/kra-agent.pem flat=yes

