---
- name: install FreeIPA master (5-7 minutes)
  tags:
    - ipaserver-master
  command: >
    ipa-server-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --hostname {{ ansible_fqdn }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ dns_forwarder.nameservers[0] }}
  args:
    creates: /etc/ipa/default.conf

- name: install KRA on FreeIPA master (2-3 minutes)
  tags:
    - ipaserver-master
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/pki/pki-tomcat/kra/CS.cfg

- name: restarted named-pkcs11 DNS server
  tags:
    - ipaserver-master
  service: name=named-pkcs11 state=restarted

- name: wait for services to come up
  tags:
    - ipaserver-master
  wait_for: port={{ item }} delay=0 timeout=30
  with_items:
    - 53
    - 88
    - 389
    - 80
    - 443

- name: sync client clocks
  tags:
    - ipaserver-master
  command: ntpdate {{ ansible_default_ipv4.address }}
  ignore_errors: yes
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipa_client'] }}"

- name: signal FreeIPA master has been deployed
  tags:
    - ipaserver-master
  file: path=/etc/ipa/MASTER_DEPLOYED state=touch

- name: change replicas' resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
  template: src=etc_resolvconf dest=/etc/resolv.conf
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipaserver_replica'] }}"

- name: change clients' resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
  template: src=etc_resolvconf dest=/etc/resolv.conf
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipa_client'] }}"

- name: change master's resolv.conf to use FreeIPA DNS
  tags:
    - ipaserver-master
  template: src=etc_resolvconf dest=/etc/resolv.conf

- name: Fetch krb5config
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/krb5.conf
         dest={{ vagrant_root }}/krb5.conf
         flat=yes

- name: Fetch cacert
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/ipa/ca.crt
         dest={{ vagrant_root }}/ca.crt
         flat=yes

- name: Fetch kra agent pem file
  tags:
    - ipaserver-master
    - fetch
  fetch: src=/etc/httpd/alias/kra-agent.pem dest={{ vagrant_root }}/kra-agent.pem flat=yes

