---
- name: DNF or YUM?
  tags:
    - common
  set_fact: dnf_package="{{ ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '22' }}"
  changed_when: false

- name: Default facts (enable_packages, enable_network)
  tags:
    - common
  set_fact: enable_packages=false enable_network=false
  changed_when: false

- name: Override enable_packages=true
  tags:
    - common
    - package-install
  set_fact: enable_packages=true
  changed_when: false

- name: Override enable_network=true
  tags:
    - common
    - network
  set_fact: enable_network=true
  changed_when: false

- name: Get nmcli device info
  tags:
    - common
  shell:
    "nmcli -t -f GENERAL.CONNECTION device show {{ ansible_default_ipv4.interface }} | awk -F: '{print $2}'"
  register: result
  changed_when: false

- name: Set nmcli device info fact
  tags:
    - common
  set_fact: nm_conn="'{{ result.stdout_lines[0] }}'"
  changed_when: false

