---
# - debug: var=hostvars[inventory_hostname] verbosity=4

- name: fix /etc/hosts
  tags:
    - common
  template: src=etc_hosts dest=/etc/hosts

- name: Set FQDN hostname
  tags:
    - common
  sudo: yes
  hostname: name={{ ansible_fqdn }}

- name: Get timedatectl information
  tags:
    - common
  command: timedatectl
  register: timedatectl
  changed_when: false

- name: Set timezone to UTC
  tags:
    - common
  command: timedatectl set-timezone UTC
  when: "'Time zone: UTC' not in timedatectl.stdout"

- name: DNF or YUM?
  tags:
    - common
  set_fact: dnf_package="{{ ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '22' }}"
  changed_when: false

- name: Default to enable_packages=false
  tags:
    - common
  set_fact: enable_packages=false
  changed_when: false

- name: Override enable_packages=true
  tags:
    - common
    - package-install
  set_fact: enable_packages=true

- include: dnf.yml
  when: dnf_package

- include: yum.yml
  when: not dnf_package

- name: Add GPG for FreeIPA 4.3 COPR
  tags:
    - common
    - package-install
    - package-copr
    - network
  rpm_key: key=https://copr-be.cloud.fedoraproject.org/results/@freeipa/freeipa-4-3/pubkey.gpg state=present

- name: Enable FreeIPA 4.3 COPR
  tags:
    - common
    - package-install
    - package-copr
    - network
  command: dnf copr enable -y @freeipa/freeipa-4-3

- name: upgrade all packages
  tags:
    - common
    - package-install
    - package-upgrade
    - network
  yum: name=* state=latest

- name: install selinux tools
  tags:
    - common
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - selinux-policy

- name: Create directory for custom RPMS
  tags:
    - common
    - custom-rpms
  file: path=/vagrant/rpms state=directory mode=0755
  changed_when: false

- name: Synchronize RPMs
  tags:
    - common
    - custom-rpms
  synchronize:
    src={{vagrant_root}}/rpms/
    dest=/vagrant/rpms/
    delete=true
    recursive=true
    copy_links=true
    rsync_opts="--exclude=README"
  changed_when: false

- name: find custom RPMs
  tags:
    - common
    - custom-rpms
  command: find -L /vagrant/rpms \( -type f -and -name '*.rpm' \) -printf '%p '
  register: custom_rpms
  changed_when: false

- name: install custom RPMs
  tags:
    - common
    - custom-rpms
  command: dnf install --allowerasing --best -y {{ custom_rpms.stdout }}
  when: custom_rpms.stdout

- name: disable selinux for 389-DS installation
  # for LXC, 389-DS installation hangs with:
  # SELinux policy is not managed or store cannot be accessed
  tags:
    - common
    - lxc
  selinux: state=disabled
  when: disable_selinux

- name: install firewalld
  tags:
    - pki
    - firewall
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
    - firewalld
    - python-firewall

- name: check for firewalld
  tags:
    - common
    - firewall
  stat: path=/usr/sbin/firewalld
  register: has_firewalld

- name: Enable and start firewalld
  tags:
    - common
    - firewall
  service: name=firewalld enabled=yes state=started
  when: has_firewalld.stat.exists

- name: Install rng tools
  tags:
    - common
    - package-install
    - network
  yum: name=rng-tools state=present

- name: Start the rngd service
  tags:
    - common
  service: name=rngd enabled=yes state=started

- name: tty-less sudo
  tags:
    - common
  lineinfile: dest=/etc/sudoers
              state=absent
              regexp='^Defaults(\s+)requiretty(\s*)$'
              validate='visudo -cf %s'
