---
# - debug: var=hostvars[inventory_hostname] verbosity=4

- name: fix /etc/hosts
  tags:
    - common
  template: src=etc_hosts dest=/etc/hosts

- name: Set FQDN hostname
  tags:
    - common
  sudo: yes
  hostname: name={{ ansible_fqdn }}

- name: Get timedatectl information
  tags:
    - common
  command: timedatectl
  register: timedatectl
  changed_when: false

- name: Set timezone to UTC
  tags:
    - common
  command: timedatectl set-timezone UTC
  when: "'Time zone: UTC' not in timedatectl.stdout"

- name: Disable repos to prevent network access
  tags:
    - common
    - network
  command: dnf config-manager --set-disabled {{ item }}
  with_items:
    - fedora
    - updates
  when: not network_access and ansible_distribution == "Fedora" and ansible_distribution_major_version >= "22"
  changed_when: false

- name: Enable repos
  tags:
    - common
    - network
  command: dnf config-manager --set-enabled {{ item }}
  with_items:
    - fedora
    - updates
  when: network_access and ansible_distribution == "Fedora" and ansible_distribution_major_version >= "22"
  changed_when: false

- name: Auto select fastest yum mirror
  tags:
    - common
  ini_file: dest=/etc/dnf/dnf.conf
            section=main
            option=fastestmirror
            value=1
            backup=yes
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= "22"

- name: Auto-select fastest yum mirror
  tags:
    - common
    - packages
    - network
  yum: name=yum-plugin-fastestmirror state=present
  when: network_access and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

- name: Keep DNF cache
  tags:
    - common
  ini_file: dest=/etc/dnf/dnf.conf
            section=main
            option=keepcache
            value=1
            backup=yes
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= "22"

- name: Enable yum for Fedora
  tags:
    - common
    - packages
    - network
  command: dnf install yum-utils -y
  when: network_access and ansible_distribution == "Fedora" and ansible_distribution_major_version >= "22"
  args:
    creates: /usr/bin/yumdownloader

- name: Add GPG for FreeIPA 4.3 COPR
  tags:
    - common
    - packages
    - network
  rpm_key: key=https://copr-be.cloud.fedoraproject.org/results/@freeipa/freeipa-4-3/pubkey.gpg state=present
  when: network_access and enable_copr

- name: Enable FreeIPA 4.3 COPR
  tags:
    - common
    - packages
    - network
  command: dnf copr enable -y @freeipa/freeipa-4-3
  when: network_access and enable_copr

- name: upgrade all packages
  tags:
    - common
    - packages
    - network
  yum: name=* state=latest
  when: network_access and upgrade_packages

- name: install selinux tools
  tags:
    - common
    - packages
    - network
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - selinux-policy
  when: network_access

- name: Create directory for custom RPMS
  tags:
    - common
    - rpm
  file: path=/vagrant/rpms state=directory mode=0755
  changed_when: false

- name: Synchronize RPMs
  tags:
    - common
    - rpm
  synchronize: src={{vagrant_root}}/rpms/ dest=/vagrant/rpms/ delete=true recursive=true copy_links=true

- name: find custom RPMs
  tags:
    - common
    - rpms
  command: find -L /vagrant/rpms \( -type f -and -name '*.rpm' \) -printf '%p '
  register: custom_rpms
  changed_when: false

- name: install custom RPMs
  tags:
    - common
    - rpms
  command: dnf install --allowerasing --best -y {{ custom_rpms.stdout }}
  when: custom_rpms.stdout

- name: disable selinux for 389-DS installation
  # for LXC, 389-DS installation hangs with:
  # SELinux policy is not managed or store cannot be accessed
  tags:
    - common
    - lxc
  selinux: state=disabled
  when: disable_selinux

- name: install firewalld
  tags:
    - pki
    - firewall
    - packages
    - network
  yum: name={{ item }} state=present
  with_items:
    - firewalld
    - python-firewall
  when: network_access

- name: check for firewalld
  tags:
    - common
  stat: path=/usr/sbin/firewalld
  register: has_firewalld

- name: Enable and start firewalld
  tags:
    - common
  service: name=firewalld enabled=yes state=started
  when: has_firewalld.stat.exists

- name: Install rng tools
  tags:
    - common
    - packages
    - network
  yum: name=rng-tools state=present
  when: network_access

- name: Start the rngd service
  tags:
    - common
  service: name=rngd enabled=yes state=started

- name: tty-less sudo
  tags:
    - common
  lineinfile: dest=/etc/sudoers
              state=absent
              regexp='^Defaults(\s+)requiretty(\s*)$'
              validate='visudo -cf %s'
