---
- name: Auto-select fastest yum mirror
  tags:
    - common
    - package-install
    - network
  yum: name=yum-plugin-fastestmirror state=present

- name: Disable repos to prevent network access
  tags:
    - common
  command: yum-config-manager --disable {{ item }}
  with_items:
    - fedora
    - updates
  when: not enable_packages
  changed_when: false

- name: Enable repos
  tags:
    - common
  command: yum-config-manager --enable {{ item }}
  with_items:
    - fedora
    - updates
  when: enable_packages
  changed_when: false