---
- name: install FreeIPA server package (Fedora)
  tags:
    - ipaserver
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
    - bind-pkcs11
    - bind-pkcs11-utils
    - bind-dyndb-ldap
    - freeipa-server
    - freeipa-server-dns
  when: ansible_distribution == "Fedora"

- name: install FreeIPA server package (RHEL / CentOS)
  tags:
    - ipaserver
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
    - bind-pkcs11
    - bind-pkcs11-utils
    - bind-dyndb-ldap
    - ipa-server
    - ipa-server-dns
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: Open Firewall for services
  tags:
    - ipaserver
    - firewall
  firewalld: 
    service={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - dns
    - kerberos
    - kpasswd
    - ntp
  when: has_firewalld.stat.exists

- name: Open Firewall for ports
  tags:
    - ipaserver
    - firewall
  firewalld:
    port={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - 9180/tcp
    - 9443-9446/tcp
    - 9701/tcp
    - 7389/tcp
    - 8443/tcp
  when: has_firewalld.stat.exists
