---
- name: install FreeIPA server package (RHEL / CentOS)
  tags:
    - ipaserver
    - package-install
    - network
  package: name={{ item }} state=present
  with_items:
    - bind-pkcs11
    - bind-pkcs11-utils
    - bind-dyndb-ldap
    - ipa-server
    - ipa-server-dns
  when: package_install

- name: Open Firewall for services
  tags:
    - ipaserver
    - firewall
  firewalld:
    service={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - freeipa-ldap
    - freeipa-ldaps
    - dns
  when: has_firewalld.stat.exists

# workaround for https://pagure.io/freeipa/issue/6704
- name: Stop Apache HTTPD to free port 8443 for installation
  tags:
    - ipaserver
  service:
    name=httpd
    state=stopped
  when: not ipa.configured.server
