---
- include: replica43.yml
  when: "ipa.version.version_info >= [4, 3, 0]"

- include: replica42.yml
  when: "ipa.version.version_info < [4, 3, 0]"

- name: Update IPA facts
  tags:
    - ipaserver-replica
  ipa_facts: domain={{ ipa_domain }}
