---
- include: ../../ipa/tasks/waitformaster.yml

- include: replica43.yml
  when: "'4.3.' in ipa_version.stdout"

- include: replica42.yml
  when: "'4.2.' in ipa_version.stdout"

- name: flag replication installation
  tags:
    - ipaserver-replica
    - ipa-install
  copy:
    content="PKI playbook"
    dest=/etc/ipa/REPLICA_INSTALLED
  changed_when: false

- include: ../../ipa/tasks/ipaclientinstalled.yml
