---
- name: Extra sleep again to prevent race condition (#5653)
  tags:
    - ipaserver-replica
    - ipa-install
    - sleep
  command: sleep 5
  args:
    creates:
      /etc/ipa/REPLICA_INSTALLED

# configure as client first, then promote to replica
- include: ../../ipa/tasks/ipaclient.yml

- name: install replica
  tags:
    - ipaserver-replica
    - ipa-install
  command: >
    ipa-replica-install -U
    --password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --mkhomedir
    --ip-address {{ ansible_default_ipv4.address }}
    --setup-dns
    {{ '--forwarder=%s' % dns_forwarder['nameservers'][0] if enable_network else '--no-forwarders' }}
  args:
    creates:
      /etc/ipa/REPLICA_INSTALLED
