---
# configure as client first, then promote to replica
- include: ../../ipa-client/tasks/main.yml

- name: install replica
  tags:
    - ipaserver-replica
    - ipa-install
  command: >
    ipa-replica-install -U
    --admin-password {{ ipa_admin_password }}
    --mkhomedir
    --ip-address {{ ansible_default_ipv4.address }}
    --setup-dns
    --allow-zone-overlap
    {{ '--forwarder=%s' % dns_forwarder['nameservers'][0] if enable_network else '--no-forwarders' }}
  args:
    creates:
      /etc/ipa/REPLICA_INSTALLED
