---
- include: ../../ipa/tasks/waitformaster.yml
- include: ../../ipa/tasks/ipaclient.yml

- name: Run ipa-client-automount
  tags:
    - ipa-client
    - ipa-install
  command:
    ipa-client-automount --unattended
  register: result
  failed_when: "result.rc != 0 and 'automount is already configured' not in result.stderr"
  changed_when: "result.rc == 0"
  notify:
    - restart autofs
