---
- include: ../../ipa/tasks/waitformaster.yml

- name: Check for /etc/ipa/default.conf
  tags:
    - ipa-client
    - install
  stat: path=/etc/ipa/default.conf
  register: ipa_default_conf

# hack, Ansible is too fast.
- name: Magic wait to make ipa-client-install work
  tags:
    - ipa-client
    - install
  command: sleep 10
  when: not ipa_default_conf.stat.exists

- name: join FreeIPA
  tags:
    - ipa-client
    - install
  command: >
    ipa-client-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --principal admin
    --password {{ ipa_admin_password }}
    --request-cert
    --force-join
  args:
    creates: /etc/ipa/default.conf
